#!/usr/bin/env python3
"""Sync the canonical 中级计量经济学 course sources from EconKB into this Quarto site.

Sources are READ-ONLY and never modified:

    <econkb>/30_教学/01_中级计量经济学（应用经济学硕士）/课程知识库/飞书课程版/
        manifest.json        -- 37 course pages: id / title / parent / source
        state.json           -- course page id -> 飞书 node_token
        textbook_links.json  -- textbook page id -> 飞书 url (+ per-heading block ids)
        lessons/*.md         -- course page bodies
        图片/                 -- course images
    <econkb>/30_教学/09_计量教材/
        拆分章节/*.md         -- 24 textbook page bodies
        图片/{教材插图,小黑,封面图}/ -- textbook images

Generated in this repo:

    index.qmd                 -- from manifest page "root"
    course/<id>.qmd           -- one per remaining manifest page
    textbook/<id>.qmd         -- one per TEXTBOOK_PAGES entry
    assets/images/*.png       -- images referenced by any synced page
    the AUTO-GENERATED block in _quarto.yml (the sidebar)

飞书 links inside the Markdown are rewritten to in-site links, so a reader who
clicks 「教材对应」 stays on the site instead of being sent to 飞书. Links whose
target is not part of this site are unwrapped to plain text.

Usage:
    python3 tools/sync_from_econkb.py --econkb ~/Documents/EconKB
    python3 tools/sync_from_econkb.py --econkb ~/Documents/EconKB --check
"""

from __future__ import annotations

import argparse
import json
import posixpath
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

from PIL import Image


COURSE_REL = Path("30_教学/01_中级计量经济学（应用经济学硕士）/课程知识库/飞书课程版")
TEXTBOOK_REL = Path("30_教学/09_计量教材")

# Textbook pages, in site order. Derived from textbook_links.json ids, but the
# order there is arbitrary, so it is pinned here.
TEXTBOOK_PAGES: list[tuple[str, str]] = [
    ("guide", "0_导读与使用说明.md"),
    ("intro", "00_导论.md"),
    ("part1", "00a_第一部分_回归分析基础.md"),
    ("ch01", "01_第1章_一元线性回归.md"),
    ("ch02", "02_第2章_多元线性回归_估计.md"),
    ("ch03", "03_第3章_多元线性回归_推断.md"),
    ("ch04", "04_第4章_模型形式扩展.md"),
    ("ch05", "05_第5章_模型设定与诊断.md"),
    ("part2", "05a_第二部分_从基础回归到复杂现实.md"),
    ("ch06", "06_第6章_离散选择模型.md"),
    ("ch07", "07_第7章_面板数据模型.md"),
    ("ch08", "08_第8章_工具变量模型.md"),
    ("ch09", "09_第9章_因果推断前沿方法.md"),
    ("ch10", "10_第10章_大数据与非经典计量.md"),
    ("part3", "10a_第三部分_从方法到实证项目.md"),
    ("ch11", "11_第11章_研究问题与识别策略.md"),
    ("ch12", "12_第12章_数据准备与变量构建.md"),
    ("ch13", "13_第13章_模型估计与结果检验.md"),
    ("ch14", "14_第14章_研究成果的呈现.md"),
    ("references", "15_参考文献.md"),
    ("appendix_math", "附录1_数学基础.md"),
    ("appendix_stata", "附录2_Stata入门.md"),
    ("appendix_python", "附录3_Python入门.md"),
    ("ending", "结束语.md"),
]

# Textbook pages reference images Obsidian-style: ![[ch01-fig1.png]]
# Pages written by hand in this repo (not part of the 飞书 manifest) that belong
# in the sidebar. Pinned here so the generated sidebar does not drop them.
EXTRA_RESOURCE_PAGES: list[tuple[str, str]] = [
    ("agent-guide.qmd", "如何让 AI Agent 辅助学习"),
]

WIKI_IMAGE_RE = re.compile(r"!\[\[([^\]]+)\]\]")

# Course pages reference images with ordinary Markdown, relative to the course
# 图片/ folder (written both as "图片/x.png" and "../图片/x.png" in the sources).
# The sub-path is preserved on the site: course 图片/xiaohei/a.png and textbook
# 小黑/a.png are different files with the same basename.
COURSE_IMAGE_RE = re.compile(r"!\[([^\]]*)\]\(((?:\.\./)?图片/([^)\s]+))\)")

FEISHU_LINK_RE = re.compile(
    r"\[([^\]]+)\]\((https://[^/\s)]+/wiki/([A-Za-z0-9]+)(?:#[A-Za-z0-9]+)?)\)"
)

SIDEBAR_BEGIN = "      # >>> AUTO-GENERATED by tools/sync_from_econkb.py -- do not edit by hand >>>"
SIDEBAR_END = "      # <<< AUTO-GENERATED <<<"

# The EconKB sources are print-resolution PNGs (mostly 2688x1536, ~6 MB each)
# because the same files feed the PDF build. A website needs neither that size
# nor that format: copying them verbatim puts ~255 MB into the repository and
# makes every push crawl. So raster images are downscaled and re-encoded here.
# The EconKB originals are never touched.
IMAGE_MAX_WIDTH = 1600
IMAGE_QUALITY = 90
RASTER_EXT_RE = re.compile(r"\.(png|jpe?g)$", re.IGNORECASE)


def load_json(path: Path) -> Any:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def build_feishu_map(course_dir: Path) -> dict[str, str]:
    """Map every 飞书 wiki token that has an in-site counterpart to its page."""
    mapping: dict[str, str] = {}

    state = load_json(course_dir / "state.json")
    for page_id, entry in state.get("pages", {}).items():
        target = "index.qmd" if page_id == "root" else f"course/{page_id}.qmd"
        for key in ("node_token", "obj_token"):
            token = entry.get(key)
            if token:
                mapping[token] = target

    links = load_json(course_dir / "textbook_links.json")
    for page_id, entry in links.get("pages", {}).items():
        match = re.search(r"/wiki/([A-Za-z0-9]+)", entry.get("url", ""))
        if match:
            mapping[match.group(1)] = f"textbook/{page_id}.qmd"

    return mapping


def relative_to(from_dir: str, target: str) -> str:
    """Path to `target` as seen from `from_dir` (both site-root-relative POSIX)."""
    from_posix = from_dir if from_dir else "."
    return posixpath.relpath(target, from_posix)


def web_name(name: str) -> str:
    """Site path for an image: rasters become .webp, anything else is unchanged."""
    return RASTER_EXT_RE.sub(".webp", name)


def write_image(source: Path, destination: Path) -> None:
    """Write one site image, downscaling and re-encoding rasters to WebP."""
    if not RASTER_EXT_RE.search(source.name):
        shutil.copy2(source, destination)  # vector, or already a web format
        return

    with Image.open(source) as image:
        width = image.width
    command = ["cwebp", "-q", str(IMAGE_QUALITY), "-quiet"]
    if width > IMAGE_MAX_WIDTH:
        command += ["-resize", str(IMAGE_MAX_WIDTH), "0"]
    command += [str(source), "-o", str(destination)]
    try:
        subprocess.run(command, check=True)
    except FileNotFoundError:
        raise SystemExit(
            "cwebp not found. Install it (`brew install webp`) or lower the "
            "image handling in write_image()."
        )


def rewrite_body(text: str, feishu_map: dict[str, str], from_dir: str) -> str:
    """Rewrite 飞书 links and wiki-style images into in-site equivalents."""

    def link_repl(match: re.Match[str]) -> str:
        label, _url, token = match.group(1), match.group(2), match.group(3)
        target = feishu_map.get(token)
        if target is None:
            # Not part of this site (e.g. 飞书-only material): keep the text only.
            return label
        return f"[{label}]({relative_to(from_dir, target)})"

    text = FEISHU_LINK_RE.sub(link_repl, text)

    def course_image_repl(match: re.Match[str]) -> str:
        alt, sub_path = match.group(1), match.group(3)
        target = f"{relative_to(from_dir, 'assets/images')}/{web_name(sub_path)}"
        return f"![{alt}]({target})"

    text = COURSE_IMAGE_RE.sub(course_image_repl, text)

    def image_repl(match: re.Match[str]) -> str:
        target = f"{relative_to(from_dir, 'assets/images')}/{web_name(match.group(1))}"
        return f"![]({target})"

    return WIKI_IMAGE_RE.sub(image_repl, text)


def collect_images(
    course_bodies: list[str],
    textbook_bodies: list[str],
    course_image_root: Path,
    textbook_image_roots: list[Path],
) -> dict[str, Path]:
    """Resolve every image referenced by a synced page.

    Returns a mapping of output path (relative to assets/images/) to source file.
    """
    result: dict[str, Path] = {}
    missing: list[str] = []

    # Textbook: ![[name]] -> assets/images/<name>, looked up across the textbook roots.
    available: dict[str, Path] = {}
    for root in textbook_image_roots:
        if root.is_dir():
            for path in root.rglob("*"):
                if path.is_file():
                    available.setdefault(path.name, path)
    for text in textbook_bodies:
        for name in WIKI_IMAGE_RE.findall(text):
            if name in result:
                continue
            source = available.get(name)
            if source is None:
                missing.append(f"textbook: {name}")
            else:
                result[name] = source

    # Course: ![](图片/<sub>) -> assets/images/<sub>, keeping the sub-path.
    for text in course_bodies:
        for _alt, _raw, sub_path in COURSE_IMAGE_RE.findall(text):
            if sub_path in result:
                continue
            source = course_image_root / sub_path
            if not source.is_file():
                missing.append(f"course: 图片/{sub_path}")
            else:
                result[sub_path] = source

    if missing:
        raise FileNotFoundError(
            "Images referenced by synced pages were not found:\n  "
            + "\n  ".join(sorted(set(missing)))
        )
    return result


def sidebar_yaml(manifest: dict[str, Any]) -> list[str]:
    """Render the site sidebar from the manifest's page tree."""
    pages = manifest["pages"]
    children: dict[str | None, list[dict[str, Any]]] = {}
    for page in pages:
        children.setdefault(page.get("parent"), []).append(page)

    def href_for(page_id: str) -> str:
        return "index.qmd" if page_id == "root" else f"course/{page_id}.qmd"

    def quote(value: str) -> str:
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'

    lines: list[str] = []

    def emit(nodes: list[dict[str, Any]], indent: int) -> None:
        pad = " " * indent
        for node in nodes:
            kids = children.get(node["id"], [])
            nested_extra = textbook_entries() if node["id"] == "textbook" else []
            if not kids and not nested_extra:
                lines.append(f"{pad}- href: {href_for(node['id'])}")
                lines.append(f"{pad}  text: {quote(node['title'])}")
                continue
            lines.append(f"{pad}- section: {quote(node['title'])}")
            lines.append(f"{pad}  href: {href_for(node['id'])}")
            lines.append(f"{pad}  contents:")
            if nested_extra:
                lines.append(f"{pad}    - section: {quote('教材正文')}")
                lines.append(f"{pad}      contents:")
                for title, target in nested_extra:
                    lines.append(f"{pad}        - href: {target}")
                    lines.append(f"{pad}          text: {quote(title)}")
            emit(kids, indent + 4)
            if node["id"] == "resources":
                child_pad = " " * (indent + 4)
                for href, text in EXTRA_RESOURCE_PAGES:
                    lines.append(f"{child_pad}- href: {href}")
                    lines.append(f"{child_pad}  text: {quote(text)}")

    def textbook_entries() -> list[tuple[str, str]]:
        titles = load_json(course_dir / "textbook_links.json")["pages"]
        return [
            (titles[page_id]["title"], f"textbook/{page_id}.qmd")
            for page_id, _filename in TEXTBOOK_PAGES
            if page_id in titles
        ]

    # Top level: manifest root's children, preceded by the homepage itself.
    root = next(page for page in pages if page["id"] == "root")
    lines.append("- href: index.qmd")
    lines.append(f"  text: {quote(root['title'])}")
    emit(children.get("root", []), 0)
    return lines


def splice_sidebar(quartoTemplate: Path, block: str) -> bool:
    """Replace the AUTO-GENERATED sidebar block. Returns True if anything changed."""
    text = quartoTemplate.read_text(encoding="utf-8")
    begin = text.find(SIDEBAR_BEGIN)
    end = text.find(SIDEBAR_END)
    if begin == -1 or end == -1:
        raise SystemExit(
            f"{quartoTemplate} is missing the AUTO-GENERATED markers; "
            "see SIDEBAR_BEGIN / SIDEBAR_END in this script."
        )
    end += len(SIDEBAR_END)
    updated = f"{text[:begin]}{SIDEBAR_BEGIN}\n{block}\n{SIDEBAR_END}{text[end:]}"
    if updated == text:
        return False
    quartoTemplate.write_text(updated, encoding="utf-8")
    return True


def write_llms_txt(repo: Path, manifest: dict[str, Any], course_dir: Path) -> None:
    """Regenerate llms.txt so agents can index every page on the site."""
    site = "https://zhang-chenglei.github.io/Econometrics-course"
    textbook_titles = load_json(course_dir / "textbook_links.json")["pages"]

    lines = [
        "# 中级计量经济学",
        "",
        "> 面向应用经济学研究生的中级计量经济学课程网站：15 讲课程页与全套教材。",
        "",
        "## 课程",
        "",
    ]
    for page in manifest["pages"]:
        target = "index.html" if page["id"] == "root" else f"course/{page['id']}.html"
        lines.append(f"- [{page['title']}]({site}/{target})")

    lines += ["", "## 教材", ""]
    for page_id, _filename in TEXTBOOK_PAGES:
        entry = textbook_titles.get(page_id)
        if entry:
            lines.append(f"- [{entry['title']}]({site}/textbook/{page_id}.html)")

    lines.append("")
    (repo / "llms.txt").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--econkb", type=Path, required=True, help="Path to the EconKB checkout")
    parser.add_argument("--check", action="store_true", help="Report drift without writing")
    args = parser.parse_args()

    global course_dir
    repo = Path(__file__).resolve().parents[1]
    course_dir = args.econkb / COURSE_REL
    textbook_dir = args.econkb / TEXTBOOK_REL

    manifest = load_json(course_dir / "manifest.json")
    feishu_map = build_feishu_map(course_dir)

    # Read every source page up front, so image collection sees the real bodies.
    course_bodies: list[tuple[str, str, str]] = []  # (page_id, body, target)
    for page in manifest["pages"]:
        source = course_dir / page["source"]
        target = "index.qmd" if page["id"] == "root" else f"course/{page['id']}.qmd"
        course_bodies.append((page["id"], source.read_text(encoding="utf-8"), target))

    textbook_bodies: list[tuple[str, str, str]] = []
    for page_id, filename in TEXTBOOK_PAGES:
        source = textbook_dir / "拆分章节" / filename
        textbook_bodies.append((page_id, source.read_text(encoding="utf-8"), f"textbook/{page_id}.qmd"))

    images = collect_images(
        [body for _, body, _ in course_bodies],
        [body for _, body, _ in textbook_bodies],
        course_dir / "图片",
        [textbook_dir / "图片"],
    )

    if args.check:
        problems = []
        for _page_id, body, target in course_bodies + textbook_bodies:
            from_dir = posixpath.dirname(target)
            expected = rewrite_body(body, feishu_map, from_dir)
            path = repo / target
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                problems.append(target)
        if problems:
            print(f"{len(problems)} page(s) out of date: " + ", ".join(problems))
            sys.exit(1)
        print("All pages up to date.")
        return

    # 1. Write the pages.
    written: set[str] = set()
    for _page_id, body, target in course_bodies + textbook_bodies:
        from_dir = posixpath.dirname(target)
        path = repo / target
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(rewrite_body(body, feishu_map, from_dir), encoding="utf-8")
        written.add(target)

    # 2. Write the images (downscaled + re-encoded, see write_image).
    image_dir = repo / "assets/images"
    image_dir.mkdir(parents=True, exist_ok=True)
    expected_images = {web_name(name) for name in images}
    for target_rel, source in images.items():
        destination = image_dir / web_name(target_rel)
        destination.parent.mkdir(parents=True, exist_ok=True)
        write_image(source, destination)

    # 3. Regenerate the sidebar.
    block = "\n".join(
        "      " + line if line.strip() else "" for line in sidebar_yaml(manifest)
    )
    changed = splice_sidebar(repo / "_quarto.yml", block)

    # 4. Regenerate llms.txt.
    write_llms_txt(repo, manifest, course_dir)

    # 5. Report orphans rather than deleting anything.
    orphans = [
        path.relative_to(repo).as_posix()
        for folder in ("course", "textbook")
        for path in sorted((repo / folder).glob("*.qmd"))
        if path.relative_to(repo).as_posix() not in written
    ]

    stale_images = [
        path.relative_to(repo).as_posix()
        for path in sorted(image_dir.rglob("*"))
        if path.is_file() and path.relative_to(image_dir).as_posix() not in expected_images
    ]

    print(f"Pages written : {len(course_bodies)} course + {len(textbook_bodies)} textbook")
    print(f"Images written: {len(images)}")
    print(f"Sidebar       : {'updated' if changed else 'unchanged'}")
    if orphans:
        print("Orphan pages (not removed, no longer in the manifest):")
        for orphan in orphans:
            print(f"  {orphan}")
    if stale_images:
        print("Stale images (not removed — e.g. the pre-WebP PNGs):")
        for stale in stale_images:
            print(f"  {stale}")


if __name__ == "__main__":
    main()
